import type { GameId } from "~/types";

/*
 * Bookmark categories:
 * - map, town, hideout, boss, pinnacle: automatic location/session markers parsed from Client.txt scene lines.
 * - manual: user-triggered markers created from the recorder overlay; these are the only user-renamable/deletable markers.
 * - death: automatic markers created from active-game death log lines.
 * - rewind-manual-replay: app-generated markers created when a manual replay is saved from rewind.
 *
 * Bookmark sources:
 * - client-log: generated by Path of Exile Client.txt lines.
 * - manual: generated by an explicit user action.
 * - system: generated by Hinekora for app events such as a manual replay save.
 */
export type BookmarkCategory =
  | "boss"
  | "death"
  | "hideout"
  | "manual"
  | "map"
  | "pinnacle"
  | "rewind-manual-replay"
  | "town";

export type BookmarkSubcategory = "abyss-depths" | "trial" | null;

export type BookmarkSource = "client-log" | "manual" | "system";
export type BookmarkLinkTargetKind = "activity-session" | "recording";
export type ActivitySessionMode = "rewind";
export type ActivitySessionClipTargetKind = "replay-clip";

export interface Bookmark {
  id: string;
  sourceGame: GameId;
  sourceLeague: string;
  source: BookmarkSource;
  category: BookmarkCategory;
  subcategory: BookmarkSubcategory;
  label: string;
  sceneName: string | null;
  note: string | null;
  occurredAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface BookmarkRecordingLink {
  id: string;
  bookmarkId: string;
  targetKind: BookmarkLinkTargetKind;
  targetId: string;
  offsetSeconds: number | null;
  durationSeconds: number | null;
  archived: boolean;
  archivedTargetTitle: string | null;
  archivedTargetDurationSeconds: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface ActivitySession {
  id: string;
  mode: ActivitySessionMode;
  sourceGame: GameId;
  sourceLeague: string;
  startedAt: string;
  stoppedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ActivitySessionClip {
  id: string;
  activitySessionId: string;
  targetKind: ActivitySessionClipTargetKind;
  targetId: string;
  bookmarkId: string | null;
  offsetSeconds: number | null;
  targetDurationSeconds: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface ActivitySessionBookmark extends Bookmark {
  offsetSeconds: number | null;
}

export interface ActivitySessionTimeline {
  bookmarks: ActivitySessionBookmark[];
  clips: ActivitySessionClip[];
  session: ActivitySession;
}

export type ActivitySessionLibrarySortKey =
  | "bookmarkCount"
  | "clipCount"
  | "durationSeconds"
  | "sourceLeague"
  | "startedAt";

export type ActivitySessionLibrarySortDirection = "asc" | "desc";

export interface ActivitySessionLibraryItem extends ActivitySession {
  bookmarkCount: number;
  clipCount: number;
  durationSeconds: number | null;
}

export interface ActivitySessionLibraryQuery {
  game?: GameId;
  league?: string;
  pageIndex?: number;
  pageSize?: number;
  sortBy?: ActivitySessionLibrarySortKey;
  sortDirection?: ActivitySessionLibrarySortDirection;
}

export interface ActivitySessionLibraryPage {
  items: ActivitySessionLibraryItem[];
  availableLeagues: string[];
  pageCount: number;
  pageIndex: number;
  pageSize: number;
  sortBy: ActivitySessionLibrarySortKey;
  sortDirection: ActivitySessionLibrarySortDirection;
  totalCount: number;
}

export interface BookmarkLibraryItem extends Bookmark {
  activeRecordingDurationSeconds: number | null;
  activeRecordingId: string | null;
  activeRecordingOffsetSeconds: number | null;
  archivedRecordingId: string | null;
  archivedRecordingTitle: string | null;
  archivedRecordingDurationSeconds: number | null;
}

export type BookmarkLibrarySortKey =
  | "category"
  | "label"
  | "occurredAt"
  | "sourceLeague";

export type BookmarkLibrarySortDirection = "asc" | "desc";

export interface BookmarkLibraryQuery {
  category?: BookmarkCategory;
  game?: GameId;
  league?: string;
  pageIndex?: number;
  pageSize?: number;
  sortBy?: BookmarkLibrarySortKey;
  sortDirection?: BookmarkLibrarySortDirection;
}

export interface BookmarkLibraryPage {
  items: BookmarkLibraryItem[];
  availableCategories: BookmarkCategory[];
  availableLeagues: string[];
  pageCount: number;
  pageIndex: number;
  pageSize: number;
  sortBy: BookmarkLibrarySortKey;
  sortDirection: BookmarkLibrarySortDirection;
  totalCount: number;
}

export interface BookmarkManualCreateResult {
  bookmark: Bookmark | null;
  error: string | null;
  ok: boolean;
}

export interface BookmarkManualUpdateInput {
  id: string;
  label: string;
  note?: string | null;
}

export interface RecordingBookmark extends Bookmark {
  offsetSeconds: number | null;
  durationSeconds: number | null;
}

export interface RecordingBookmarksQuery {
  pageIndex?: number;
  pageSize?: number;
}

export interface RecordingBookmarksPage {
  items: RecordingBookmark[];
  pageCount: number;
  pageIndex: number;
  pageSize: number;
  timelineItems: RecordingBookmark[];
  totalCount: number;
}
