/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttributionsRouteImport } from './routes/attributions'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as CaptureGuideRouteImport } from './routes/capture-guide'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ClipsRouteImport } from './routes/clips'
import { Route as CropOverlayRouteImport } from './routes/crop-overlay'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as RewindsRouteImport } from './routes/rewinds'
import { Route as SavedEditsRouteImport } from './routes/saved-edits'
import { Route as SavedVideosRouteImport } from './routes/saved-videos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ClipClipIdRouteImport } from './routes/clip.$clipId'
import { Route as RecordingRecordingIdRouteImport } from './routes/recording.$recordingId'
import { Route as RewindRewindIdRouteImport } from './routes/rewind.$rewindId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionsRoute = AttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureGuideRoute = CaptureGuideRouteImport.update({
  id: '/capture-guide',
  path: '/capture-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipsRoute = ClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const CropOverlayRoute = CropOverlayRouteImport.update({
  id: '/crop-overlay',
  path: '/crop-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewindsRoute = RewindsRouteImport.update({
  id: '/rewinds',
  path: '/rewinds',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedEditsRoute = SavedEditsRouteImport.update({
  id: '/saved-edits',
  path: '/saved-edits',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedVideosRoute = SavedVideosRouteImport.update({
  id: '/saved-videos',
  path: '/saved-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipClipIdRoute = ClipClipIdRouteImport.update({
  id: '/clip/$clipId',
  path: '/clip/$clipId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingRecordingIdRoute = RecordingRecordingIdRouteImport.update({
  id: '/recording/$recordingId',
  path: '/recording/$recordingId',
  getParentRoute: () => rootRouteImport,
} as any)
const RewindRewindIdRoute = RewindRewindIdRouteImport.update({
  id: '/rewind/$rewindId',
  path: '/rewind/$rewindId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/bookmarks': typeof BookmarksRoute
  '/capture-guide': typeof CaptureGuideRoute
  '/changelog': typeof ChangelogRoute
  '/clips': typeof ClipsRoute
  '/crop-overlay': typeof CropOverlayRoute
  '/editor': typeof EditorRoute
  '/recordings': typeof RecordingsRoute
  '/rewinds': typeof RewindsRoute
  '/saved-edits': typeof SavedEditsRoute
  '/saved-videos': typeof SavedVideosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/recording/$recordingId': typeof RecordingRecordingIdRoute
  '/rewind/$rewindId': typeof RewindRewindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/bookmarks': typeof BookmarksRoute
  '/capture-guide': typeof CaptureGuideRoute
  '/changelog': typeof ChangelogRoute
  '/clips': typeof ClipsRoute
  '/crop-overlay': typeof CropOverlayRoute
  '/editor': typeof EditorRoute
  '/recordings': typeof RecordingsRoute
  '/rewinds': typeof RewindsRoute
  '/saved-edits': typeof SavedEditsRoute
  '/saved-videos': typeof SavedVideosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/recording/$recordingId': typeof RecordingRecordingIdRoute
  '/rewind/$rewindId': typeof RewindRewindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributions': typeof AttributionsRoute
  '/bookmarks': typeof BookmarksRoute
  '/capture-guide': typeof CaptureGuideRoute
  '/changelog': typeof ChangelogRoute
  '/clips': typeof ClipsRoute
  '/crop-overlay': typeof CropOverlayRoute
  '/editor': typeof EditorRoute
  '/recordings': typeof RecordingsRoute
  '/rewinds': typeof RewindsRoute
  '/saved-edits': typeof SavedEditsRoute
  '/saved-videos': typeof SavedVideosRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/clip/$clipId': typeof ClipClipIdRoute
  '/recording/$recordingId': typeof RecordingRecordingIdRoute
  '/rewind/$rewindId': typeof RewindRewindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributions'
    | '/bookmarks'
    | '/capture-guide'
    | '/changelog'
    | '/clips'
    | '/crop-overlay'
    | '/editor'
    | '/recordings'
    | '/rewinds'
    | '/saved-edits'
    | '/saved-videos'
    | '/settings'
    | '/setup'
    | '/clip/$clipId'
    | '/recording/$recordingId'
    | '/rewind/$rewindId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributions'
    | '/bookmarks'
    | '/capture-guide'
    | '/changelog'
    | '/clips'
    | '/crop-overlay'
    | '/editor'
    | '/recordings'
    | '/rewinds'
    | '/saved-edits'
    | '/saved-videos'
    | '/settings'
    | '/setup'
    | '/clip/$clipId'
    | '/recording/$recordingId'
    | '/rewind/$rewindId'
  id:
    | '__root__'
    | '/'
    | '/attributions'
    | '/bookmarks'
    | '/capture-guide'
    | '/changelog'
    | '/clips'
    | '/crop-overlay'
    | '/editor'
    | '/recordings'
    | '/rewinds'
    | '/saved-edits'
    | '/saved-videos'
    | '/settings'
    | '/setup'
    | '/clip/$clipId'
    | '/recording/$recordingId'
    | '/rewind/$rewindId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionsRoute: typeof AttributionsRoute
  BookmarksRoute: typeof BookmarksRoute
  CaptureGuideRoute: typeof CaptureGuideRoute
  ChangelogRoute: typeof ChangelogRoute
  ClipsRoute: typeof ClipsRoute
  CropOverlayRoute: typeof CropOverlayRoute
  EditorRoute: typeof EditorRoute
  RecordingsRoute: typeof RecordingsRoute
  RewindsRoute: typeof RewindsRoute
  SavedEditsRoute: typeof SavedEditsRoute
  SavedVideosRoute: typeof SavedVideosRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ClipClipIdRoute: typeof ClipClipIdRoute
  RecordingRecordingIdRoute: typeof RecordingRecordingIdRoute
  RewindRewindIdRoute: typeof RewindRewindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributions': {
      id: '/attributions'
      path: '/attributions'
      fullPath: '/attributions'
      preLoaderRoute: typeof AttributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-guide': {
      id: '/capture-guide'
      path: '/capture-guide'
      fullPath: '/capture-guide'
      preLoaderRoute: typeof CaptureGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clips': {
      id: '/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof ClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-overlay': {
      id: '/crop-overlay'
      path: '/crop-overlay'
      fullPath: '/crop-overlay'
      preLoaderRoute: typeof CropOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewinds': {
      id: '/rewinds'
      path: '/rewinds'
      fullPath: '/rewinds'
      preLoaderRoute: typeof RewindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-edits': {
      id: '/saved-edits'
      path: '/saved-edits'
      fullPath: '/saved-edits'
      preLoaderRoute: typeof SavedEditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-videos': {
      id: '/saved-videos'
      path: '/saved-videos'
      fullPath: '/saved-videos'
      preLoaderRoute: typeof SavedVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$clipId': {
      id: '/clip/$clipId'
      path: '/clip/$clipId'
      fullPath: '/clip/$clipId'
      preLoaderRoute: typeof ClipClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording/$recordingId': {
      id: '/recording/$recordingId'
      path: '/recording/$recordingId'
      fullPath: '/recording/$recordingId'
      preLoaderRoute: typeof RecordingRecordingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewind/$rewindId': {
      id: '/rewind/$rewindId'
      path: '/rewind/$rewindId'
      fullPath: '/rewind/$rewindId'
      preLoaderRoute: typeof RewindRewindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionsRoute: AttributionsRoute,
  BookmarksRoute: BookmarksRoute,
  CaptureGuideRoute: CaptureGuideRoute,
  ChangelogRoute: ChangelogRoute,
  ClipsRoute: ClipsRoute,
  CropOverlayRoute: CropOverlayRoute,
  EditorRoute: EditorRoute,
  RecordingsRoute: RecordingsRoute,
  RewindsRoute: RewindsRoute,
  SavedEditsRoute: SavedEditsRoute,
  SavedVideosRoute: SavedVideosRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ClipClipIdRoute: ClipClipIdRoute,
  RecordingRecordingIdRoute: RecordingRecordingIdRoute,
  RewindRewindIdRoute: RewindRewindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
